# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aba826a4be81f429c79fb3830840557326bf516bcd14c86467160816ed7e4f26b425ac40dc542ffa51ecf1df11682d3c9efa0c419e3f73008956cf7401278a4a

test:
  secret_key_base: fa544a64a151c951d11f5c9f6c684249f0c91131ed72b9220e36690416e6dfc912b4501d84576b3731eb7536c20be0385f36726d0af49f4621aca0b47776c5cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
